In [2]:
import pandas as pd

In [6]:
'''Data Aggregation of Singapur Airline Reviews'''

df_1 = pd.read_csv('tripadvisor_airline_sq_batch_100.csv', index_col=0)
df_2 = pd.read_csv('tripadvisor_airline_sq_batch_200.csv', index_col=0)
df_3 = pd.read_csv('tripadvisor_airline_sq_batch_400.csv', index_col=0)
df_4 = pd.read_csv('tripadvisor_airline_sq_batch_600.csv', index_col=0)
df_5 = pd.read_csv('tripadvisor_airline_sq_batch_1000.csv', index_col=0)

frames = [df_1, df_2, df_3, df_4, df_5]
df = pd.concat(frames)

df.info

<bound method DataFrame.info of           _id  title                                               text  \
0    CKft8mKl    NaN  Für eine Reise nach Australien habe einen Flug...
1    APi7FxgK    NaN  Sitzkomfort war sehr gut, Service war schlecht...
2    QWxS8nx1    NaN  Überschrift,\nSchlimmster Flug bis jetzt.\nIn ...
3    IdGeqkxH    NaN  Sehr guter, sehr gutes Essen, luxuriöse Sitze ...
4    cSxL4ztc    NaN  ich wurde nicht befördert weil mein Reisepass,...
..        ...    ...                                                ...
360  gIItY5iU    NaN  Das Essen konnte vorab aus einer Auswahl an Ge...
361  z7bmn2Jo    NaN  Sehr aufmerksame Crew, Essen könnte besser sei...
362  NSJw0CIA    NaN  Nette Stewardessen, gutes Platzangebot, gute U...
363  Y13Qc6Km    NaN  Service der Extraklasse. Aufmerksam, unaufdrin...
364  KGBUnGHq    NaN  Sehr freundliche Stewardessen. Sehr gutes Esse...

     rating  reviewer_handle  language        airline_name  flight_date  \
0       1.0              NaN       NaN  Singapore Airlines          NaN
1       3.0              NaN       NaN  Singapore Airlines          NaN
2       2.0              NaN       NaN  Singapore Airlines          NaN
3       5.0              NaN       NaN  Singapore Airlines          NaN
4       1.0              NaN       NaN  Singapore Airlines          NaN
..      ...              ...       ...                 ...          ...
360     5.0              NaN       NaN  Singapore Airlines          NaN
361     4.0              NaN       NaN  Singapore Airlines          NaN
362     5.0              NaN       NaN  Singapore Airlines          NaN
363     5.0              NaN       NaN  Singapore Airlines          NaN
364     5.0              NaN       NaN  Singapore Airlines          NaN

     flight_connection  flight_type  booking_class
0                  NaN          NaN            NaN
1                  NaN          NaN            NaN
2                  NaN          NaN            NaN
3                  NaN          NaN            NaN
4                  NaN          NaN            NaN
..                 ...          ...            ...
360                NaN          NaN            NaN
361                NaN          NaN            NaN
362                NaN          NaN            NaN
363                NaN          NaN            NaN
364                NaN          NaN            NaN

[865 rows x 11 columns]>

In [11]:
'''Rating histogram'''
df[df['rating'] == 3.0]

,_id,title,text,rating,reviewer_handle,language,airline_name,flight_date,flight_connection,flight_type,booking_class
1,APi7FxgK,NaN,"Sitzkomfort war sehr gut, Service war schlecht...",3.0,NaN,NaN,Singapore Airlines,NaN,NaN,NaN,NaN
6,6hyNRwjV,NaN,Früher war Singapore Airlines immer unsere Lie...,3.0,NaN,NaN,Singapore Airlines,NaN,NaN,NaN,NaN
9,XvcLvmmq,NaN,Zwischen Shangri-la hotels und Singapore Airli...,3.0,NaN,NaN,Singapore Airlines,NaN,NaN,NaN,NaN
10,yZwTtFSH,NaN,Ich bin im April/Mai'23 mit Singapore Airlines...,3.0,NaN,NaN,Singapore Airlines,NaN,NaN,NaN,NaN
15,sc8m0s29,NaN,SQ wirbt mit seinem außergewöhnlichen Service....,3.0,NaN,NaN,Singapore Airlines,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
271,wy8InFy2,NaN,Für unsere Reise nach Singapur war Singapore A...,3.0,NaN,NaN,Singapore Airlines,NaN,NaN,NaN,NaN
323,5iVZazeT,NaN,Angenehmer Flug mit einer etwas älteren B777 (...,3.0,NaN,NaN,Singapore Airlines,NaN,NaN,NaN,NaN
324,H9yepT6b,NaN,Ich hatte bis anhin immer gute Erfahrungen mit...,3.0,NaN,NaN,Singapore Airlines,NaN,NaN,NaN,NaN
330,sFaCr1wz,NaN,Seit langem wieder einmal ein Flug mit der SQ....,3.0,NaN,NaN,Singapore Airlines,NaN,NaN,NaN,NaN
344,uiusrUH0,NaN,"Der Hinflug war vom Service her absolut top, w...",3.0,NaN,NaN,Singapore Airlines,NaN,NaN,NaN,NaN

In [12]:
'''Load merged dataset of Singapore Airline Reviews into one csv-file'''

df.to_csv('tripadvisor_singapore_airline_reviews.csv', encoding='UTF-8')